const { setResponseHeaders } = require("../utils/utils");

const errors = {
    "-4078": "No connection to the database."
};

const codes = {
    500: ["-4078"]
}

/**
 * Send the current errors to the user and the database.
 * @param {Object} req The request object generated by "ExpressJs".
 * @param {Object} res The response object generated by "ExpressJs".
 * @param {Object} errors An object containing a two key value pairs that represent the error code and the list of errors to display.
 */
function sendErrors(req, res, errors) {
    const { code, list } = errors;

    setResponseHeaders(req, res)
        .status(code)
        .send(JSON.stringify({ Errors: list }));
};

module.exports = () => (req, res, next) => {
    req.errorHandling = {
        sendErrors: (...params) => sendErrors(req, res, ...params)
    };

    next();
};