/**
 * Sets the response headers.
 * @param {Object} req The request object generated by "ExpressJs".
 * @param {Object} res The response object generated by "ExpressJs".
 * @param {Array} additionalHeaders An array of objects with a single key value pair named - (header, value).
 * @returns the "ExpressJs" res.set() function setting the headers in order to keep it chainable, thus preventing the need to call it again in the parent function.
 */
function setResponseHeaders(req, res, additionalHeaders) {
    const origin = checkOrigin(req);
    const headers = {
        "Content-Type": "application/json",
        "Access-Control-Allow-Origin": origin,
        "Access-Control-Expose-Headers": "Content-Type",
        "Access-Control-Allow-Credentials": "true",
        "Access-Control-Allow-Methods": "GET, POST",
        "Access-Control-Allow-Headers": "headers, method, content-type, body, id",
    };

    if (additionalHeaders) {
        for (const { header, value } of additionalHeaders) headers[header] = value;
    };
    
    return res.set(headers);
};

/**
 * Default response in place of the 404 page.
 * @param {Object} res The response object generated by "ExpressJs".
 * @param {String} message Optional message (if any).
 */
function send404(res, message) {
    const error = message ? message : "You shouldn't be doing this...";
    res.send(JSON.stringify({ Errors: error }, null, 4))
};


/**
 * Checks if the origin is in the allowed list.
 * @param {Object} req The request object generated by "ExpressJs".
 * @returns the origin if it's allowed or null.
 */
function checkOrigin(req) {
    const { origin } = req.headers;
    const allowedOrigins = [
        "https://192.168.0.185:3000",
        "https://localhost:3000"
    ];
    console.log(origin);
    return allowedOrigins.includes(origin) ? origin : null;
};

module.exports = {
    setResponseHeaders,
    send404
};